<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE messages [
<!ELEMENT messages (message)*>
<!ELEMENT message (name , website? , comment , date , user_ip? , user_agent? , spam)>
<!ATTLIST message mID ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT website (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT spam (#PCDATA)>
<!ELEMENT user_ip (#PCDATA)>
<!ELEMENT user_agent (#PCDATA)>
]>
<messages>
<message mID="m55247e15cecad68.10608001"><name>wqer</name><website/><comment>sdfdsaaaaaaaaaaa</comment><date>1380442460</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message><message mID="m15247e2d8cc87c0.32018342"><name>qwerwqer</name><website/><comment>wer</comment><date>1380442840</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message><message mID="m35247e32ac66e67.07161138"><name>1111</name><website/><comment>1111</comment><date>1380442922</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message><message mID="m45247e342173bb1.59366854"><name>2222</name><website/><comment>2222</comment><date>1380442946</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message><message mID="m15247e3890cdfc2.89917464"><name>1111111111</name><website/><comment>111111111111</comment><date>1380443016</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message><message mID="m45247e3b1193387.26329464"><name>qwer</name><website/><comment>其二</comment><date>1380443057</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message><message mID="m55247e3d28acf95.71296638"><name>1</name><website/><comment>1</comment><date>1380443090</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message><message mID="m55247e3fd45f7a6.82461212"><name>3</name><website/><comment>3</comment><date>1380443133</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message><message mID="m45247e43257d8f1.02923167"><name>2</name><website/><comment>2</comment><date>1380443186</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message><message mID="m15247e47b8ddd90.68137359"><name>3</name><website/><comment>3</comment><date>1380443259</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message><message mID="m35247e49548ab51.03149887"><name>请额外人</name><website/><comment>qwer</comment><date>1380443285</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message><message mID="m35247e52a236820.00202305"><name>2</name><website/><comment>:)</comment><date>1380443434</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message><message mID="m55247e63d298016.85911054"><name>123</name><website/><comment>123</comment><date>1380443709</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message><message mID="m45247e6688acb60.74228709"><name>234</name><website/><comment>2344</comment><date>1380443752</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message><message mID="m15247e6a683f187.21557260"><name>1</name><website/><comment>1</comment><date>1380443814</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message><message mID="m15247e7258ac739.94962074"><name>2</name><website/><comment>2</comment><date>1380443941</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message><message mID="m45247e9592a1aa4.83748780"><name>qwer</name><website></website><comment>qwer</comment><date>1380444505</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.11 Safari/537.36</user_agent><spam>0</spam></message></messages>
